### PR TITLE
Add AppleTV Support

### PR DESCRIPTION
**Pull request by hxhlb**
I modified it against #27  and it worked.
The difference is that I changed the Download log level to debug and added a bit of output.
Please verify.

Execution renderings: http://www.hxhlb.org/atv.png

### CODE REVIEW

**Comment by majd** [comment]
I don't really see how this adds support for downloading Apple TV apps. The changes do exactly what #27 did. The downloaded IPA package is for the iOS app and not the Apple TV app.

**Comment by hxhlb** [comment]
Yes, the code is the same.
Maybe the App Store has been adjusted recently, but it is indeed possible to download programs for AppleTV.
And I also found that when downloading, you can omit the --device-family option.
The Miao Project program is only available in the AppleTV platform store, of course it is paid.
Refer to the running screenshot:

http://www.hxhlb.org/atv2.png


If you have an AppleTV, you can find a dedicated AppleTV program to download and verify it.
I don't know how to determine whether the downloaded ipa belongs to IPhone or iPad or AppleTV, do you have a way to verify it?

**Comment by majd** [comment]
I think he IPA variant that is downloaded is for the iOS version. Please verify that by looking at the `CFBundleSupportedPlatforms` in the Info.plist file.

**Comment by hxhlb** [comment]
I tested 3 APPs, 2 are exclusive to AppleTV, one is YouTubeTV, YouTubeTV's CFBundleSupportedPlatforms is iPhoneOS, and the other 2 are exclusive to AppleTVOS.
http://www.hxhlb.org/atv3.png

**Comment by majd** [comment]
I see, thanks for checking. Do you have a way to test the installing the ipa package to an Apple TV?

So it seems that if the app was only available for tvOS, it would download that copy of the app otherwise it defaults to the iOS version. We would need to explicitly find a way request the tvOS copy of the app for this to be usable in the tool.

**Comment by hxhlb** [comment]
I own an AppleTV, I'll check if I can use Apple Configurator2 to install the ipa to the AppleTV

**Comment by hxhlb** [comment]
I can't capture ATV's HTTPS data. Is there any way?

**Comment by majd** [comment]
I'm not sure to be honest. I assume you can use Xcode to install the ipa package OTA from "Devices & Simulators" window.

**Comment by majd** [comment]
Is this still being worked on? Otherwise, I'd close this PR for now.

**Comment by hxhlb** [comment]
你的邮件我收到了，有机会就看见了！

**Comment by tmm1** [comment]
@hxhlb did you find any way to request tvOS ipa? if you can use Configurator to install apps maybe the request params can be seen there?

**Pull request closed without merging**
