### PR TITLE
Upstream a bunch of fixes and improvements

### LINKED ISSUE #145: Rand is always the same
### What happened?

Your rand is not seeded, so it always generates the same deterministic values:
- https://github.com/majd/ipatool/blob/main/pkg/util/rand.go

I would like to ask though, why is this necessary in the first place? If you're downloading an app and a file with that name + version already exists, why add a random suffix at the end? IMO, ipatool should either replace the file or skip it (maybe --skip-existing flag?). Would be neat for automation too.

### Version

2.0.2

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ViRb3**
Apologies for the fat PR, but it would have been too much effort to separate them. I did my best to isolate the changes in commits, so please go one by one to see the features and choose which ones you would like to merge (hopefully all). A list of changes with small descriptions:
- [Always apply user agent](https://github.com/majd/ipatool/commit/c9dd47f023206fbf206d06031c83eac01b18d61a)
  - Makes all requests use a default user agent of Configurator, instead of Go's default user agent
- [Support purchase of Arcade games](https://github.com/majd/ipatool/commit/0575a3effc603d37f5897ee2fc8056ad407532a9)
  - Allows you to purchase and download Arcade games
- [Rework filename generation](https://github.com/majd/ipatool/commit/079a608612a6df9131fedd2ed3d086c8da1efdeb)
  - Sanitizes the IPA file name, also resolves #145
- [Enable skip existing file](https://github.com/majd/ipatool/commit/5c3221731d3f42464617ae492ceaf9dbb2c541c4)
  - Adds `--skip-existing` flag, IMO useful for automation
- [Enable download of unlisted apps](https://github.com/majd/ipatool/commit/be1fe04e617b80e3b8b626fe6451bbd0bf71ed93)
  - Makes ipatool use appID internally instead of bundleID, which avoids the lookup call. This means that as long as you own an app, even if it's unlisted, you will be able to download it using its appID. Sadly, this leads to a breaking change to the IPA version that ipatool sees, since the bundle version is sometimes different from the iTunes one, and the latter is impossible to fetch in a delisted app. Sure, we could lookup if possible, and fallback to bundle version as last resort, but IMO this inconsistency is bad and so this commit always uses the bundle version. This change also adds the `--dry-run` flag, which is again useful for automation, e.g. allows you to skip downloading the app under certain conditions.
- [Expose lookup command](https://github.com/majd/ipatool/commit/9f5f67b27821e605b897ab76b20524ce21f9c83b)
  - Just a cheap and useful function

Only one small problem left — I added and updated tests for every commit except for [Enable download of unlisted apps](https://github.com/majd/ipatool/pull/148/commits/be1fe04e617b80e3b8b626fe6451bbd0bf71ed93), since a ton of test cases broke and I don't have the time (or knowledge) to fix them. I am hoping you could lend a hand here. FWIW, I tested these commits very extensively in practice and there were no issues at all.

Thanks!

### CODE REVIEW

**Comment by majd** [comment]
Thank you for putting in all the effort to improving ipatool! I really appreciate it.

As the current PR is quite big, could you please split those changes into separate PRs? One PR per line item listed above. I would be happy to help getting those changes merged!

**Comment by ViRb3** [comment]
Sure. I created as many PRs as I could which didn't conflict, will submit the rest after these are merged so I can rebase.

**Comment by hykilpikonna** [comment]
Thanks for the pr! The ability to download unlisted apps works!

For people who stumble upon this in the future: Since this branch is deleted, you cannot clone @ViRb3's repo and checkout the branch, so I cloned majd/ipatool first and used the gh command line CLI to checkout the pr: `gh pr checkout 148`. Then you can run `go build -o ipatool`. For the `cmd/root.go:20:18: undefined: version` error, just edit `cmd/root.go` and change `version` to any string value.

image

**Comment by ViRb3** [comment]
All the code will be merged upstream soon, I'd recommend just waiting a few more weeks.

**Comment by ViRb3** [comment]
For now, I have released my fork of ipatool with all personal changes, including everything in this PR:
- https://github.com/ViRb3/ipatool/

If all of them get upstreamed, I will remove this fork, but for now there's quite a few things that I find valuable and missing from here.

**Pull request closed without merging**
