### PR TITLE
Default to FileBackend keyring when other options are not available

### PR DESCRIPTION
**Pull request by majd**

### CODE REVIEW

**Comment by majd** [comment]
Fixes #196 and #139

**Comment by Geczy** [comment]
@majd doesn't seem like this fixed it. running on pi 

`Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux`

```json
{"level":"error","error":"failed to get account: failed to get item: The specified item could not be found in the keyring","success":false,"time":"2023-06-16T21:27:16-05:00"}
```

**Comment by Geczy** [comment]
i had to turn off non-interactive mode and then i saw this prompt

```
9:30PM INF enter passphrase to unlock "/home/pi/.ipatool" (this is separate from your Apple ID password): 
```

and then i could continue with the rest of the app

**Comment by Geczy** [comment]
how do i do this without a password so that its truly non interactive?

**Pull request merged**
